---
# The YAML header specifies several settings for the survey but is not required.
# A full list of settings can be found under _survey/settings.yml directory.

theme-settings:
  theme: default
  barposition: top
  footer-left: "Made with [surveydown](https://surveydown.org)"
  footer-right: '[<i class="bi bi-github"></i> Source Code](https://github.com/surveydown-dev/template_live_polling)'

survey-settings:
  show-previous: false
  use-cookies: false
  auto-scroll: false
  rate-survey: false
  system-language: en
  highlight-unanswered: true
  highlight-color: blue
  capture-metadata: true
  all-required: false
  required:
    - penguins
---

```{r}
library(surveydown)
```

--- welcome

# Template - Live Polling

Here is a basic "multiple choice" question. The results will be displayed on the next page, showing both the choice you made as well as a summary of all the choices made by other participants.

```{r}
sd_question(
  type  = 'mc',
  id    = 'penguins',
  label = "Which type of penguin do you like the best?",
  option = c(
    'Adélie'    = 'adelie',
    'Chinstrap' = 'chinstrap',
    'Gentoo'    = 'gentoo'
  )
)
```

--- results

You chose: **`r sd_output("penguins", type = "value")`**

Summary of what everyone else has chosen:

```{r}
shiny::plotOutput('penguin_plot')
```
